FROM apache/airflow:2.10.5-python3.12

# 사용자 권한으로 실행 (Airflow 기본 권한)
USER airflow

# pipeline에서 쓰는 패키지 설치
# 최상위 루트의 requirements.txt를 사용하도록 docker-compose에서 컨텍스트 설정
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
